name: Test OpenAI Conversation Plus

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        pip install -e .

    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: Run tests with pytest
      run: |
        pytest --cov=custom_components.openai_conversation_plus --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  hassfest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Hassfest validation
      uses: home-assistant/actions/hassfest@master
      with:
        path: "custom_components/openai_conversation_plus"

  hacs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: HACS validation
      uses: hacs/action@main
      with:
        category: integration
