name: Validate

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
        with:
          path: "custom_components/openai_conversation_plus"
